server:
  port: 8085

spring:
  application:
    name: cadastro-service
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: 123456
#  redis:
#    url: localhost
#    port: 6379

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cadastro}?currentSchema=${DB_SCHEMA:public}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
