server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: produtor-fila-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456