version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: "cardsapi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - /docker/postgres/cardsapi:/var/lib/postgresql/data
    networks:
      - api
    ports:
      - "5433:5432"

  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - api

  # pgadmin4:
  #   image: dpage/pgadmin4:4.10
  #   container_name: "pgadmin4"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin@gmail.com"
  #   ports:
  #     - "8082:80"
  #   networks:
  #     - api

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    networks:
      - api
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

networks:
  api:
    driver: bridge

volumes:
  cache:
    driver: local



