server:
  port: 8200

spring:
  application:
    name: autentication-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:autenticacao}?currentSchema=${DB_SCHEMA:public}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0
#  config:
#    import: "optional:configserver:"
springdoc:
  api-docs:
    path: autentication-service/v3/api-docs
  show-actuator: true
