server:
  port: 8080
  servlet:
    context-path: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  #  config:
  #    import: "optional:configserver:"
zuul:
  sensitive-headers: Cookie
